//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMTelmate.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int IDUser { get; set; }
        public string SurnameUser { get; set; }
        public string NameUser { get; set; }
        public string PatronumicUser { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
    }
}
